#!/bin/bash
# SPDX-License-Identifier: MIT

# Run tox. Additionally, if LSR_MSCENARIOS is defined, run `tox -e molecule`
# for every scenario from LSR_MSCENARIOS and for every Ansible version from
# LSR_ANSIBLES.
#
# LSR_MSCENARIOS is a space separated list of molecule scenarios.
# LSR_ANSIBLES is a space separated list of Ansible package names with versions
# in pip format, i.e 'ansible ansible==2.6 ansible==2.7 ansible=2.8'.
#
# LSR_MSCENARIOS and LSR_ANSIBLES can be set in .travis/config.sh or as
# environment variables.

SCRIPTDIR=$(realpath $(dirname $0))

# Include library and config.
. ${SCRIPTDIR}/utils.sh
. ${SCRIPTDIR}/config.sh

(set -x; tox); E=$?
for X in ${LSR_ANSIBLES}; do
  for Y in ${LSR_MSCENARIOS}; do
    (set -x; LSR_ANSIBLE_DEP="${X}" LSR_MSCENARIO=${Y} tox -e molecule) || E=$?
  done
done

exit $E
